# Chapter 3: Basic Reactivity

## Introduction

-   The key idea of reactive programming is to specify a graph of dependencies so that when an input changes, all related outputs are automatically updated.

## The Server Function

-   The `server` is more complicated because every user needs to get an independent version of the app; when user A moves a slider, user B shouldn't see their outputs change.

-   Shiny invokes your `server()` function each time a new session starts.

Server functions take three parameters: `input`, `output`, and `session`.

### Input

-   Unlike a typical list, input objects are read only.

-   You cannot update them within R

-   To read from an `input`, you must be in a **reactive context** created by a function like [`renderText()`](https://rdrr.io/pkg/shiny/man/renderPrint.html) or [`reactive()`](https://rdrr.io/pkg/shiny/man/reactive.html).

### Output

-   Also a list--like object

-   You always need to use it with a `render` function

-   The output ID is used with quotations "quoted" in the ui but not in the server

-   You'll get an error if you forget the `render` function or attempt to read from an output

## Reactive Programming

-   Reactivity means that outputs automatically update as inputs change

-   The app works because the code doesn't *tell* Shiny to create the string and send it to the browser but instead informs *how* *it could* create the string if it needs to.

### Imperative Versus Declarative Programming

-   In **imperative** programming, you issue a specific command and it's carried out immediately. This is the style of programming you're used to in your analysis scripts: you command R to load your data, transform it, visualise it, and save the results to disk.

-   In **declarative** programming, you express higher-level goals or describe important constraints, and rely on someone else to decide how and/or when to translate that into action. This is the style of programming you use in Shiny.

-   Imperative code is assertive; declarative code is passive-aggressive.

### Laziness

-   Shiny doesn't update the output if you can't see it in the browser.

-   If you're working on a Shiny app and you just can't figure out why your code never gets run, double check that your UI and server functions are using the same identifiers.

### The Reactive Graph

-   You can understand an R code by looking at it from top to bottom. This doesn't apply to Shiny because code is only run when needed.

-   To undertand an R Shiny app, you can use a *reactive graph* : it describes how inputs and outputs are connected.

-   Example: `greeting` gets recomputed whenever `name` is changed. This means that `greeting` has a *relative dependency* on `name` .

-   You can view the graph using `reactlog` package.

### Reactive Expressions

-   *Reactive Expression*: a tool that reduces duplication in your reactive code by introducing additional nodes into the reactive graph. This node has angles on both sides.

### Execution Order

-   This is different from most R code where the execution order is determined by the order of lines. For example, we could flip the order of the two lines and it would still work.

-   It's best to stick to the order of what humans are used to. This is referred to as *topological sort*.

-   The order in which reactive code is run is determined only by the reactive graph, not by its layout in the server function.

### Exercises

## Reactive expressions

-   Input : Producers

-   Outputs: Consumers

-   Inputs and expressions are reactive producers; expressions and outputs are reactive consumers
